### ISSUE TITLE
Automatic generation of the match tree

### ISSUE THREAD

**Issue by JeremLa** [JeremLa/Tournament-Factory#13]
**Is your feature request related to a problem? Please describe.**
A tournament is a succession of matches, and for now it's not possible to generate them.

**Describe the solution you'd like**
Give to application the capability to generate maches of one tournament. Assignate participants of match is not an avaible feature, so just display tree of matches of tournament without them for now.

**Additional context**
Think about futur and possibility to give the hand to user for generating tree, edit matches manually or even better automatic generation with auto assignement of participant.

**Comment by ahermes** [comment]
Generating is done, the visual will be done in next version
