### ISSUE TITLE
Create single-elimination tournament

### ISSUE THREAD

**Issue by JeremLa** [JeremLa/Tournament-Factory#9]
**Is your feature request related to a problem? Please describe.**
The heart of application is tournament, it's time to give user opportunity to create it.

**Describe the solution you'd like**
A tournament is a name, a number of max participent en a collection of match.

For now, the goal is to give tools to user for create his own tournaments, list them, update them and delete them.

**Additional context**
Do not forget, this is the first type of tournament, think right now about future.

**Comment by ahermes** [comment]
Not finished during Sprint3 , continued in Sprint4 with #52
